ResitalTurizmWEB.UI/Controllers/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ResitalTurizmWEB.BUSINESS.Abstract;
using ResitalTurizmWEB.BUSINESS.Concrete;
using ResitalTurizmWEB.DATA.Abstract;
using ResitalTurizmWEB.DATA.Concrete;
using ResitalTurizmWEB.ENTITY.Entities;
using ResitalTurizmWEB.MODELS.Common;
using ResitalTurizmWEB.UI.Identity;
using ResitalTurizmWEB.UI.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;

namespace ResitalTurizmWEB.UI.Controllers
{
    public class BookingController : Controller
    {
        private IBookingRepository<Booking> bookingRepository = new BookingRepository();
        private IBookingRepository<Room> roomRepository = new RoomRepository();
        private BookingManager bookingManager = new BookingManager();
        private BookingViewModel bookingViewModel = new BookingViewModel();
        private IBookingService _bookingService;
        private UserManager<User> _userManager;
        public BookingController(IBookingService bookingService, UserManager<User> userManager)
        {
            this._bookingService = bookingService;
            _userManager = userManager;
        }

        [Authorize(Roles = "admin")]
        public IActionResult Index(int? id, int? otelId)
        {
            var bookingViewModel = new BookingViewModel()
            {
                Bookings = _bookingService.GetBookingsByOtel(otelId)
            };
            TempData["bookingId"] = otelId;
            bookingViewModel.YearToDisplay = (id == null) ? DateTime.Today.Year : id.Value;
            return View(bookingViewModel);
        }

        // GET: Booking/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Booking booking = bookingRepository.Get(id.Value);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        [Authorize]
        public IActionResult Create(int roomId)
        {
            DateTime today = DateTime.Today;
            DateTime tomorrow = DateTime.Today.AddDays(1);
            //var room = _bookingService.GetRoom(roomId);
            var room = roomRepository.Get(roomId);
            var model = new Booking()
            {
                RoomId = roomId,
                EndDate = tomorrow,
                StartDate = today,
                OtelId = room.OtelId,
                UserId = _userManager.GetUserId(User),
        };
            
            //ViewData["CustomerId"] = new SelectList(customerRepository.GetAll(), "Id", "Name", booking.UserId);

            return View(model);
        }

        [HttpPost]
        public IActionResult GetRoomPrice(int roomId, DateTime startDate, DateTime endDate)
        {
            var fark = endDate - startDate;
            var totalDays = fark.TotalDays;
            var room = roomRepository.Get(roomId);
            var result = room.Fiyat * totalDays;
            

            return PartialView("~/Views/Shared/_roomPrice.cshtml", result);
        }

        // POST: Bookings/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("StartDate,EndDate,UserId,RoomId,OtelId")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                ServiceCallResult created = bookingManager.CreateBooking(booking);

                if (created.Success)
                {
                    TempData["SuccessNotification"] = created.SuccessMessages;
                    //return RedirectToAction(nameof(Index));
                    return View(booking);
                }
                else
                {
                    TempData["ErrorNotification"] = created.ErrorMessages;
                    return View(booking);
                }
            }

            //ViewData["CustomerId"] = new SelectList(customerRepository.GetAll(),"Id", "Name", booking.UserId);
            ViewBag.Status = "Rezervasyon oluşturulamadı, mevcut oda bulunmamakta.";
            return View(booking);
        }

        // GET: Booking/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Booking booking = bookingRepository.Get(id.Value);
            if (booking == null)
            {
                return NotFound();
            }
            //ViewData["CustomerId"] = new SelectList(customerRepository.GetAll(), "Id", "Name", booking.UserId);
            ViewData["RoomId"] = new SelectList(roomRepository.GetAll(), "Id", "Description", booking.RoomId);
            return View(booking);
        }

        // POST: Booking/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,StartDate,EndDate,IsActive,UserId,RoomId,OtelId")] Booking booking)
        {
            if (id != booking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    bookingRepository.Edit(booking);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (bookingRepository.Get(booking.Id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("~/booking/index");
                
            }
            //ViewData["CustomerId"] = new SelectList(customerRepository.GetAll(), "Id", "Name", booking.UserId);
            ViewData["RoomId"] = new SelectList(roomRepository.GetAll(), "Id", "Description", booking.RoomId);
            return View(booking);
        }

        // GET: Booking/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Booking booking = bookingRepository.Get(id.Value);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Booking/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            bookingRepository.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ResitalTurizmWEB.UI/Controllers/OtelController.cs
using Microsoft.AspNetCore.Mvc;
using ResitalTurizmWEB.BUSINESS.Abstract;
using ResitalTurizmWEB.DATA.Concrete.EfCore;
using ResitalTurizmWEB.ENTITY;
using ResitalTurizmWEB.ENTITY.Entities;
using ResitalTurizmWEB.UI.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;

namespace ResitalTurizmWEB.UI.Controllers
{
    
    public class OtelController : Controller
    {

        ResitalContext db = new ResitalContext();

        private IOtelService _otelService;
        public OtelController(IOtelService otelService)
        {
            this._otelService = otelService;
        }
        // localhost/otels/yurtdışı?page=1
        public IActionResult List(string categoryotel, int page=1)
        {
            const int pageSize = 3; //sabit tanımladım, her sayfada kaç ürün gösterilsin
            var otelViewModel = new OtelListViewModel()
            {
                PageInfo = new PageInfo()
                {
                  ToTalItems = _otelService.GetCountByCategory(categoryotel),
                  CurrentPage = page,
                  ItemsPerPage = pageSize,
                  CurrentCategoryOtel = categoryotel
                },
                Oteller = _otelService.GetOtelsByCategoryOtel(categoryotel, page, pageSize)
            };
            return View(otelViewModel);
        }

        public IActionResult Details(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            Otel otel = _otelService.GetOtelDetails((int)id);

            if (otel==null)
            {
                return NotFound();
            }
            return View(new OtelDetailModel
            {
                Otel = otel,
                CategoryOtel = otel.CategoryOtel 
            });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Otel o) 
        {
            return View();
        }

        public IActionResult Search(string q, DateTime startDate, DateTime endDate)
        {
            var otelViewModel = new OtelListViewModel()
            {
                Oteller = _otelService.GetSearchResult(q,startDate,endDate)
            };
            return View(otelViewModel);
        }

        //public IActionResult Odalar(string name)
        //{

        //        var rooms = db.Room
        //            .Where(i => (string.IsNullOrEmpty(name) || i.OtelAd.ToLower() == name.ToLower()));
        //        var otel = db.Oteller
        //               .Where(i => (string.IsNullOrEmpty(name) || i.OtelAdı.ToLower() == name.ToLower())).Select(i => i.OtelAdı).FirstOrDefault();
        //            ViewBag.otel = otel;
                 
        //        return View(rooms);
            
        //}
    }
}

ResitalTurizmWEB.UI/Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using ResitalTurizmWEB.BUSINESS.Abstract;
using System;
using ResitalTurizmWEB.UI.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ResitalTurizmWEB.UI.Controllers
{
    public class RoomController : Controller
    {
        private IRoomService _roomService;
        private IOtelService _otelService;
        public RoomController(IRoomService roomService, IOtelService otelService)
        {
            this._roomService = roomService;
            this._otelService = otelService;
        }

        

        public IActionResult List(int otelId)
        {
            var RoomListViewModel = new RoomListViewModel()
            {
                Odalar = _roomService.GetRoomsByOtel(otelId)
                
            };
            return View(RoomListViewModel);
        }
    }
}

ResitalTurizmWEB.UI/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ResitalTurizmWEB.DATA.Abstract;
using ResitalTurizmWEB.DATA.Concrete;
using ResitalTurizmWEB.ENTITY.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading.Tasks;

namespace ResitalTurizmWEB.UI.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoomsController : Controller
    {
        private IBookingRepository<Room> repository = new RoomRepository();

        // GET: Rooms
        public IActionResult Index()
        {
            return View(repository.GetAll().ToList());
        }

        // GET: Rooms/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Room room = repository.Get(id.Value);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,OtelId,OtelAd,Fiyat,Description,ImageUrl")] Room room)
        {
            if (ModelState.IsValid)
            {
                repository.Add(room);
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Room room = repository.Get(id.Value);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,OtelId,OtelAd,Fiyat,Description,ImageUrl")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    repository.Edit(room);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (repository.Get(room.Id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Room room = repository.Get(id.Value);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (id > 0)
                repository.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ResitalTurizmWEB.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] - ResitalTurizmWEB.UI</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"> @*isapproved icon için*@
    <link rel="stylesheet" href="~/template/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/template/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/template/css/datepicker.css" />
    <link rel="stylesheet" type="text/css" href="~/template/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="~/template/slick/slick-theme.css" />
    <link rel="stylesheet" href="~/template/css/templatemo-style.css">

    <link href="~/css/toastr.min.css" rel="stylesheet" />

    @RenderSection("Css", false)
</head>
<body>

    @await Html.PartialAsync("_navbar")


    <main role="main" class="pb-3 my3">
        @if (TempData["message"] != null) //Tempdata, .Net Core tarafında Session objesini kullanır.
        {
            var message = JsonConvert.DeserializeObject<AlertMessage>(TempData["message"] as string);
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-@message.AlertType">
                        @message.Message
                    </div>
                </div>
            </div>
        }
        @RenderBody()
    </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now - ResitalTurizm <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/template/js/jquery-1.11.3.min.js"></script>
    <script src="~/template/js/popper.min.js"></script>
    <script src="~/template/js/bootstrap.min.js"></script>
    <script src="~/template/js/datepicker.min.js"></script>
    <script src="~/template/js/jquery.singlePageNav.min.js"></script>
    <script src="~/template/slick/slick.min.js"></script>
    <script src="~/template/js/jquery.scrollTo.min.js"></script>


    <script src="~/js/sweetalert2.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script>
        toastr.options = {
            "closeButton": true,
            "newestOnTop": false,
            "progressBar": true,
            "positionClass": "toast-bottom-left",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "3000",
            "hideDuration": "3000",
            "timeOut": "10000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>

    @if (TempData["SuccessNotification"] != null)
    {
        @foreach (var item in (IList<string>)TempData["SuccessNotification"])
        {
            <script>  toastr.success("@item.ToString()");</script>
        }
    }
    @if (TempData["ErrorNotification"] != null)
    {
        @foreach (var item in (IList<string>)TempData["ErrorNotification"])
        {
            <script>  toastr.error("@item.ToString()");</script>
        }
    }


    @await RenderSectionAsync("Scripts", required: false)
    @*@RenderSection("Scripts", required: false)*@

    <script>
        /* DOM is ready
        ------------------------------------------------*/
        $(function () {

            // Change top navbar on scroll
            $(window).on("scroll", function () {
                if ($(window).scrollTop() > 100) {
                    $(".tm-top-bar").addClass("active");
                } else {
                    $(".tm-top-bar").removeClass("active");
                }
            });

            // Smooth scroll to search form
            $('.tm-down-arrow-link').click(function () {
                $.scrollTo('#tm-section-search', 300, { easing: 'linear' });
            });

            // Date Picker in Search form
            var pickerCheckIn = datepicker('#inputCheckIn');
            var pickerCheckOut = datepicker('#inputCheckOut');

            // Update nav links on scroll
            $('#tm-top-bar').singlePageNav({
                currentClass: 'active',
                offset: 60
            });

            // Slick Carousel
            $('.tm-slideshow').slick({
                infinite: true,
                arrows: true,
                slidesToShow: 1,
                slidesToScroll: 1
            });
        });

    </script>
</body>
</html>

ResitalTurizmWEB.UI/Views/Shared/_categories.cshtml
@*@model List<CategoryOtel>*@

ResitalTurizmWEB.UI/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ResitalTurizmWEB.UI</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

ResitalTurizmWEB.UI/Views/Shared/_navbar.cshtml
<div class="tm-main-content" id="top">
    <div class="tm-top-bar-bg"></div>
    <div class="tm-top-bar" >
        <div class="container">
            <div class="row">
                <nav class="navbar navbar-expand-lg narbar-light">
                    <a class="navbar-brand mr-auto" href="/home/index">
                        <img src="~/template/img/logo.png" alt="Site logo">
                        Resital
                    </a>
                    <button type="button" id="nav-toggle" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#mainNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div id="mainNav" class="collapse navbar-collapse tm-bg-white">
                        <ul class="navbar-nav m-auto">
                            <li class="nav-item">
                                <a class="nav-link active" href="/home/index">Anasayfa <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a href="/otels" class="nav-link">Otel</a>
                            </li>
                            <li class="nav-item">
                                <a href="/home/gemi" class="nav-link">Gemi</a>
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a href="/orders" class="nav-link">Rezervasyonlarım</a>
                                </li>
                            }
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Admin
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a asp-controller="admin" asp-action="otellist" class="dropdown-item"><b>Otel</b></a>
                                        <a asp-controller="admin" asp-action="rolelist" class="dropdown-item"><b>Rol</b></a>
                                        <a asp-controller="admin" asp-action="userlist" class="dropdown-item"><b>Kullanıcı</b></a>
                                        <a asp-controller="booking" asp-action="index" class="dropdown-item"><b>Rezervasyon</b></a>
                                        <a asp-controller="rooms" asp-action="index" class="dropdown-item"><b>Odalar</b></a>
                                    </div>
                                </li>
                            }
                        </ul>
                        <ul class="navbar-nav ml-auto">

                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a href="/cart" class="nav-link">Sepet</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="account" asp-action="Manage" class="nav-link">@User.Identity.Name</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="account" asp-action="Logout" class="nav-link">Çıkış</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a asp-controller="account" asp-action="Login" class="nav-link">Giriş</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="account" asp-action="Register" class="nav-link">Kayıt Ol</a>
                                </li>
                            }




                        </ul>
                    </div>
                </nav>
            </div>
        </div> 
    </div> 
</div>

ResitalTurizmWEB.UI/Views/Shared/_nootel.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_nootel</title>
</head>
<body>
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                Otel Yok
            </div>
        </div>
    </div>
</body>
</html>

ResitalTurizmWEB.UI/Views/Shared/_otel.cshtml
@model Otel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_otel</title>
    
</head>
<body>
    
    <div class="card mb-1">
        <img class="card-img-top" src="~/template/img/@Model.ImageUrl" alt="" />
        <div class="card-body">
            <h5 class="card-title">@Model.OtelAdı</h5>
            <small class="text-muted">
                <i class="fas fa-lira-sign">@(Model.Fiyat + " ₺")</i>
            </small>
        </div>
        <div class="card-footer text-center">
            <a asp-controller="Otel" asp-action="Details" asp-route-id="@Model.OtelID" class="btn btn-primary btn-sm">
                Detaylar
            </a>
            <a asp-controller="Room" asp-action="List" asp-route-otelId="@Model.OtelID" class="btn btn-primary btn-sm">Odalar</a>
        </div>
    </div>
</body>
</html>

ResitalTurizmWEB.UI/Views/Shared/_room.cshtml
@model Room

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_room</title>
    
</head>
<body>
    <h2>@ViewBag.otel</h2>
    <h2>@ViewBag.SelectedOtel</h2>
    <div class="card mb-1">
        <img class="card-img-top" src="~/template/img/@Model.ImageUrl" alt="" />
        <div class="card-body">
            <h5 class="card-title">@Model.Otel.OtelAdı</h5>
            <small class="text-muted">
                <i class="fas fa-lira-sign">@(Model.Fiyat + " ₺")</i>
            </small>
        </div>
        <div class="card-footer text-center">
            <a asp-controller="Booking" asp-action="Create" asp-route-roomId="@Model.Id" class="btn btn-primary btn-sm">Rezervasyon</a>

        </div>
    </div>
</body>
</html>

ResitalTurizmWEB.UI/Views/Shared/_roomPrice.cshtml
@model Double

<div class="form-group">
    <label class="control-label">Fiyat</label>
    <input type="text" name="Fiyat" disabled class="form-control" id="Fiyat" value="@Model" />
</div>